### PR TITLE
Django 2.2

### PR DESCRIPTION
**Pull request by miggol**
It has finally come to this. A django-1.11 branch has been made to keep a working copy of the old version.

### CODE REVIEW

**Comment by tymees** [comment]
>  A django-1.11 branch has been made to keep a working copy of the old version.

Wouldn't a git tag be a better way to do this?

**Comment by miggol** [comment]
I have changed the common.yaml of im-linux-etcl to pull from the new django-1.11 branch.

**Comment by tymees** [comment]
Fair point

Still would like a tag, so we can remove that branch when we decommission the old servers

**Comment by miggol** [comment]
> Fair point
> 
> Still would like a tag, so we can remove that branch when we decommission the old servers

What do you mean exactly by this? A tag on the dango-1.11 branch to remind us to remove it?

**Comment by tymees** [comment]
> What do you mean exactly by this? A tag on the dango-1.11 branch to remind us to remove it?

A tag on master before we pull in the django 2.2 code. Otherwise the tag would be removed if the django-1.11 branch is removed

**Pull request merged**
